# Generated by Django 4.1.2 on 2022-11-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='department',
            field=models.CharField(choices=[('two', 'Pharma'), ('one', 'vet')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.products'),
        ),
    ]
